<?xml version="1.0" encoding="utf-8"?>
<Project>
  <!-- https://learn.microsoft.com/nuget/consume-packages/central-package-management -->
  <ItemGroup>
    <PackageVersion Include="CppAst" Version="0.22.0" />

    <PackageVersion Include="Silk.NET.Shaderc.Native" Version="2.23.0" />

    <!-- Samples -->
    <PackageVersion Include="ppy.SDL3-CS" Version="2026.722.0" />
    
    <!-- Tests -->
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="18.10.1" />
    <PackageVersion Include="NUnit" Version="5.0.0" />
    <PackageVersion Include="NUnit3TestAdapter" Version="6.3.0" />
  </ItemGroup>

</Project>
